// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly VITE_URL_BACKOFFICE: string
  readonly VITE_ENEDIS_SANDBOX_PRM: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
