// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly URL_BACKOFFICE: string
  readonly ENEDIS_SANDBOX_PRM: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
